/**
 * Render Module
 * Converts review JSON to Markdown format.
 */

import { ReviewResult, Finding, Severity } from './types';

const SEVERITY_EMOJI: Record<Severity, string> = {
  blocker: ':no_entry:',
  major: ':warning:',
  minor: ':information_source:',
  nit: ':bulb:',
};

const SEVERITY_LABEL: Record<Severity, string> = {
  blocker: 'Blocker',
  major: 'Major',
  minor: 'Minor',
  nit: 'Nit',
};

const RISK_EMOJI: Record<string, string> = {
  low: ':white_check_mark:',
  medium: ':yellow_circle:',
  high: ':red_circle:',
};

export const COMMENT_MARKER = '<!-- llm-pr-reviewer -->';

/**
 * Render a finding reference as a string.
 */
function renderRef(finding: Finding): string {
  const { ref, file } = finding;

  if (ref.type === 'line_range' && ref.start_line != null) {
    if (ref.end_line != null && ref.end_line !== ref.start_line) {
      return `${file}:${ref.start_line}-${ref.end_line}`;
    }
    return `${file}:${ref.start_line}`;
  }

  if (ref.type === 'diff_hunk' && ref.hunk_header) {
    return `${file} (${ref.hunk_header})`;
  }

  return file;
}

/**
 * Render a single finding as Markdown.
 */
function renderFinding(finding: Finding): string {
  const emoji = SEVERITY_EMOJI[finding.severity];
  const label = SEVERITY_LABEL[finding.severity];
  const ref = renderRef(finding);

  const lines: string[] = [
    `### ${emoji} ${label}: ${finding.title}`,
    '',
    `**Location:** \`${ref}\``,
    '',
    finding.detail,
    '',
  ];

  return lines.join('\n');
}

/**
 * Render the full review result as Markdown.
 */
export function renderReviewMarkdown(result: ReviewResult, headSha?: string): string {
  const lines: string[] = [];

  // Marker for sticky comment
  lines.push(COMMENT_MARKER);
  lines.push('');

  // Header
  lines.push('# :robot: LLM PR Review');
  if (headSha) {
    lines.push(`*Reviewed commit: \`${headSha.substring(0, 7)}\`*`);
  }
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push(result.summary);
  lines.push('');

  // Risk Assessment
  const riskEmoji = RISK_EMOJI[result.risk.level] || ':question:';
  lines.push(`## Risk Assessment ${riskEmoji}`);
  lines.push(`**Level:** ${result.risk.level.toUpperCase()}`);
  lines.push('');
  lines.push(result.risk.rationale);
  lines.push('');

  // Findings
  if (result.findings.length > 0) {
    lines.push('## Findings');
    lines.push('');

    // Group findings by severity
    const blockers = result.findings.filter((f) => f.severity === 'blocker');
    const majors = result.findings.filter((f) => f.severity === 'major');
    const minors = result.findings.filter((f) => f.severity === 'minor');
    const nits = result.findings.filter((f) => f.severity === 'nit');

    // Show counts
    const counts: string[] = [];
    if (blockers.length > 0) counts.push(`:no_entry: ${blockers.length} blocker(s)`);
    if (majors.length > 0) counts.push(`:warning: ${majors.length} major`);
    if (minors.length > 0) counts.push(`:information_source: ${minors.length} minor`);
    if (nits.length > 0) counts.push(`:bulb: ${nits.length} nit(s)`);

    if (counts.length > 0) {
      lines.push(counts.join(' | '));
      lines.push('');
    }

    // Render all findings
    result.findings.forEach((finding) => {
      lines.push(renderFinding(finding));
    });
  } else {
    lines.push('## Findings');
    lines.push(':white_check_mark: No significant issues found.');
    lines.push('');
  }

  // Tests
  if (result.tests.add.length > 0 || result.tests.run.length > 0) {
    lines.push('## Recommended Tests');
    lines.push('');

    if (result.tests.add.length > 0) {
      lines.push('**Tests to add:**');
      result.tests.add.forEach((test) => {
        lines.push(`- ${test}`);
      });
      lines.push('');
    }

    if (result.tests.run.length > 0) {
      lines.push('**Commands to run:**');
      lines.push('```bash');
      result.tests.run.forEach((cmd) => {
        lines.push(cmd);
      });
      lines.push('```');
      lines.push('');
    }
  }

  // Questions
  if (result.questions.length > 0) {
    lines.push('## Questions for Author');
    result.questions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q}`);
    });
    lines.push('');
  }

  // Coverage Note
  if (result.coverage_note) {
    lines.push('<details>');
    lines.push('<summary>Coverage Note</summary>');
    lines.push('');
    lines.push(result.coverage_note);
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('*This review was generated by an LLM and is advisory only. Please use your judgment.*');

  return lines.join('\n');
}

/**
 * Render a fallback Markdown when the review failed.
 * Note: Raw LLM output is intentionally NOT included in PR comments to prevent
 * potential exposure of sensitive data. Raw output is logged to Actions logs instead.
 */
export function renderFallbackMarkdown(error: string, headSha?: string): string {
  const lines: string[] = [];

  lines.push(COMMENT_MARKER);
  lines.push('');
  lines.push('# :robot: LLM PR Review');
  if (headSha) {
    lines.push(`*Attempted review of commit: \`${headSha.substring(0, 7)}\`*`);
  }
  lines.push('');
  lines.push(':warning: **Review could not be completed**');
  lines.push('');
  lines.push(`Error: ${error}`);
  lines.push('');
  lines.push('Please proceed with manual review.');
  lines.push('');
  lines.push('---');
  lines.push('*This review was generated by an LLM and is advisory only. Please use your judgment.*');

  return lines.join('\n');
}
